### ISSUE TITLE
local imports

### ISSUE THREAD

**Issue by why-blip** [zwegner/sprdpl#1]
Hi,

tried to run `example.py`, the imports didn't work. I had to put `lex.py` and `parse.py` in a `./sprdpl`folder and then change the imports to `from sprdpl import lex, parse`.

**Comment by zwegner** [comment]
Thanks for the report. I knew about this, but didn't know a good way to solve it (I'd just been running `python -m sprdpl.example` from the parent directory). But after reading PEP-366 it turns out there's a not-too-awful solution, which I've added.
